---
- hosts: localhost
  connection: local

  tasks:
  - debug:
      msg: "before we run our role"
  - import_role:
      name: geerlingguy.docker
  - include_role:
      name: geerlingguy.docker
  - debug:
      msg: "after we ran our role"
